variable "dev_suffix" {}
variable "staging_suffix" {}
variable "dns_cname_records" {}
variable "default_tags" {}
variable "shared_rg_name" {}
variable "base_name" {}
variable "location" {}
variable "key_vault_names" {}
variable "key_vault_sku" {}
variable "key_vault_enable_rbac_authorization" {}
variable "key_vault_purge_protection_enabled" {}
variable "key_vault_soft_delete_retention_days" {}
variable "tls_certificates" {}
